#title: BT-5010-Lot
#description: “EU Funds Financing Identifier” The corresponding XML element is /*/cac:ProcurementProjectLot[cbc:ID/@schemeName='Lot']/cac:TenderingTerms/ext:UBLExtensions/ext:UBLExtension/ext:ExtensionContent/efext:EformsExtension/efac:Funding/efbc:FinancingIdentifier. The expected ontology instances are epo: epo:Lot / epo:Fund / adms:Identifier / rdf:PlainLiteral .
#xpath: /*/cac:ProcurementProjectLot[cbc:ID/@schemeName='Lot']/cac:TenderingTerms/ext:UBLExtensions/ext:UBLExtension/ext:ExtensionContent/efext:EformsExtension/efac:Funding/efbc:FinancingIdentifier

PREFIX adms: <http://www.w3.org/ns/adms#>
PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

ASK WHERE { 
	?this rdf:type epo:Lot .
	?this epo:isFundedBy / adms:identifier / skos:notation ?value . 
}