#title: BT-5071-Procedure
#description: “Place Performance Country Subdivision” The corresponding XML element is /*/cac:ProcurementProject/cac:RealizedLocation/cac:Address/cbc:CountrySubentityCode. The expected ontology instances are epo: epo:Procedure / epo:ContractTerm / dct:Location / locn:Address / at-voc:nuts .
#xpath: /*/cac:ProcurementProject/cac:RealizedLocation/cac:Address/cbc:CountrySubentityCode

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX locn: <http://www.w3.org/ns/locn#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
	?this rdf:type epo:Procedure .
	?this epo:foreseesContractSpecificTerm / epo:definesSpecificPlaceOfPerformance / locn:address / epo:hasNutsCode ?value . 
}