#title: BT-156-NoticeResult
#description: “Group Framework Maximum Value” The corresponding XML element is /*/ext:UBLExtensions/ext:UBLExtension/ext:ExtensionContent/efext:EformsExtension/efac:NoticeResult/efac:GroupFramework/efbc:GroupFrameworkMaximumValueAmount. The expected ontology instances are epo: epo:LotGroupAwardInformation / epo:MonetaryValue / xsd:decimal .
#xpath: /*/ext:UBLExtensions/ext:UBLExtension/ext:ExtensionContent/efext:EformsExtension/efac:NoticeResult/efac:GroupFramework/efbc:GroupFrameworkMaximumValueAmount

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
	?this rdf:type epo:LotGroupAwardInformation .
	?this epo:hasGroupFrameworkAgreementMaximumValue / epo:hasAmountValue ?value . 
}