#title: Unique ID ASK GH issue 273 TED-929/TED-1151
#description: Checks that there are no instances with multiple IDs on any of the generated individuals (e.g. epo:Contract)
#xpath: None

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX adms: <http://www.w3.org/ns/adms#>

ASK {
   {
    SELECT (COUNT(?sub) AS ?instanceCount) {
      {
       SELECT ?sub (COUNT(?obj) AS ?pCount) WHERE {
         ?sub adms:identifier ?obj .
         ?obj a adms:Identifier .
       }
       GROUP BY ?sub
      }
      FILTER (?pCount > 1)
    }
   }
   FILTER(?instanceCount = 0)
}