#title: BT-127-notice
#description: The corresponding XML element is /*/cbc:PlannedDate. 
#xpath: /*/cbc:PlannedDate

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
	?this rdf:type epo:PlannedProcurement .
	?this epo:isSubjectToTerm / epo:hasEstimatedContractNoticePublicationDate ?value. 
}