#title: BT-3201-Tender
#description: “Tender Identifier” The corresponding XML element is /*/ext:UBLExtensions/ext:UBLExtension/ext:ExtensionContent/efext:EformsExtension/efac:NoticeResult/efac:LotTender/efac:TenderReference/cbc:ID. The expected ontology instances are epo: epo:Tender / adms:Identifier / rdf:PlainLiteral .
#xpath: /*/ext:UBLExtensions/ext:UBLExtension/ext:ExtensionContent/efext:EformsExtension/efac:NoticeResult/efac:LotTender/efac:TenderReference/cbc:ID

PREFIX adms: <http://www.w3.org/ns/adms#>
PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

ASK WHERE { 
	?this rdf:type epo:Tender .
	?this adms:identifier / skos:notation ?value . 
}