#title: BT-701-notice-Scheme
#description: The corresponding XML element is /*/cbc:ID[@schemeName='notice-id']/@schemeName. The expected ontology instances are epo: epo:Notice / adms:Identifier / rdf:PlainLiteral .
#xpath: /*/cbc:ID[@schemeName='notice-id']/@schemeName

PREFIX adms: <http://www.w3.org/ns/adms#>
PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
	?this rdf:type epo:Notice .
	?this adms:identifier / epo:hasScheme ?value . 
}