#title: BT-201-Contract-Language
#description: The corresponding XML element is /*/ext:UBLExtensions/ext:UBLExtension/ext:ExtensionContent/efext:EformsExtension/efac:ContractModification/efac:ChangeReason/efbc:ReasonDescription/@languageID. The expected ontology instances are epo: epo-con:ContractModificationInformation / rdf:langString .
#xpath: /*/ext:UBLExtensions/ext:UBLExtension/ext:ExtensionContent/efext:EformsExtension/efac:ContractModification/efac:ChangeReason/efbc:ReasonDescription/@languageID

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX epo-con: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
	?this rdf:type epo-con:ContractModificationInformation .
	?this epo:hasModificationReasonDescription ?value .   FILTER(datatype(?value) = rdf:langString) 
}