#title: BT-784-Review
#description: The corresponding XML element is /*/ext:UBLExtensions/ext:UBLExtension/ext:ExtensionContent/efext:EformsExtension/efac:Appeals/efac:AppealInformation/efbc:AppealID. The expected ontology instances are epo: epo:ReviewRequest /  adms:Identifier / skos:notation .
#xpath: /*/ext:UBLExtensions/ext:UBLExtension/ext:ExtensionContent/efext:EformsExtension/efac:Appeals/efac:AppealInformation/efbc:AppealID

PREFIX adms: <http://www.w3.org/ns/adms#>
PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

ASK WHERE { 
	?this rdf:type epo:ReviewRequest .
	?this adms:identifier / skos:notation ?value . 
}