#title: BT-04-notice
#description: “Procedure Identifier” The corresponding XML element is /*/cbc:ContractFolderID. The expected ontology instances are epo: epo-not:CompetitionNotice / epo:Procedure .
#xpath: /*/cbc:ContractFolderID

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX epo-not: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
	?this rdf:type epo-not:CompetitionNotice .
	?this epo:announcesProcedure ?value . 
}