#title: Unique ID SELECT GH issue 273 TED-929/TED-1151
#description: Finds instances with multiple IDs on any of the generated individuals (e.g. epo:Contract)
#xpath: None

PREFIX epo: <http://data.europa.eu/a4g/ontology#>

SELECT ?sub ?pCount WHERE {
      {
       SELECT ?sub (COUNT(?obj) AS ?pCount) WHERE {
         ?sub adms:identifier ?obj .
         ?obj a adms:Identifier .
       }
       GROUP BY ?sub
      }
      FILTER (?pCount > 1)
}