#title: OPT-001-notice
#description: The corresponding XML element is /*/cbc:UBLVersionID. 
#xpath: /*/cbc:UBLVersionID

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

ASK WHERE { 
	?this rdf:type epo:Notice .
	?this epo:hasSpecificationInformation / epo:hasSourceVersionSpecification / skos:notation ?value . 
}