#title: BT-740-Procedure-Buyer
#description: “Buyer Contracting Entity” The corresponding XML element is /*/cac:ContractingParty/cac:ContractingPartyType/cbc:PartyTypeCode[@listName='buyer-contracting-type']. The expected ontology instances are epo: epo:Buyer / xsd:boolean .
#xpath: /*/cac:ContractingParty/cac:ContractingPartyType/cbc:PartyTypeCode[@listName='buyer-contracting-type']

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
	?this rdf:type epo:Buyer .
	?this epo:isContractingEntity false . 
}