#title: BT-21-Part-Language
#description: The corresponding XML element is /*/cac:ProcurementProjectLot[cbc:ID/@schemeName='Part']/cac:ProcurementProject/cbc:Name/@languageID. The expected ontology instances are epo: epo:PlannedProcurementPart / rdf:langString .
#xpath: /*/cac:ProcurementProjectLot[cbc:ID/@schemeName='Part']/cac:ProcurementProject/cbc:Name/@languageID

PREFIX dct: <http://purl.org/dc/terms/>
PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
	?this rdf:type epo:PlannedProcurementPart .
	?this dct:title ?value .   FILTER(datatype(?value) = rdf:langString) 
}