#title: Test absence of orphaned entities aka dangling individuals
#description: Checks for non-existence of orphans or "dangling" individuals/instances, i.e. RDF resources (entities) that do not have any incoming relationships
#xpath: None
#was: TED-929/TED-932

PREFIX adms: <http://www.w3.org/ns/adms#>
PREFIX cccev: <http://data.europa.eu/m8g/>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX epd: <http://data.europa.eu/a4g/resource/>
PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX fnml: <http://semweb.mmlab.be/ns/fnml#>
PREFIX fno: <https://w3id.org/function/ontology#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX idlab-fn: <http://example.com/idlab/function/>
PREFIX locn: <http://www.w3.org/ns/locn#>
PREFIX org: <http://www.w3.org/ns/org#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX ql: <http://semweb.mmlab.be/ns/ql#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rml: <http://semweb.mmlab.be/ns/rml#>
PREFIX rr: <http://www.w3.org/ns/r2rml#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX tedm: <http://data.europa.eu/a4g/mapping/sf-rml/>
PREFIX time: <http://www.w3.org/2006/time#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

# An "orphan" is an _unreferenced_ RDF subject resource -- a node that lacks
# connections to other parts of the graph, similar to a typographic orphan.
# It's like a word or line of text that stands alone at the bottom of a
# paragraph. In database parlance, an orphaned record has no incoming
# references or relationships. In networking terms, it's akin to a data packet
# that has no corresponding acknowledgment or reference. While orphans may very
# well be a valid occurrence, they may sometimes signal data errors.

# TODO: check behaviour with other co-existing data like ontology, likely needs additional guards

# This is a negated version of the SELECT counterpart

ASK {
    FILTER NOT EXISTS {
        ?s ?p ?o
        FILTER (isIRI(?s))
        FILTER NOT EXISTS {
            ?s0 ?p0 ?s
            FILTER(?p0 not in (rdf:type))
        }
    }
}
