#title: ND-Part
#description: The corresponding XML element is /*/cac:ProcurementProjectLot[cbc:ID/@schemeName='Part']. The expected ontology instances are epo: epo:PlannedProcurementPart  .
#xpath: /*/cac:ProcurementProjectLot[cbc:ID/@schemeName='Part']

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
	?this rdf:type epo:PlannedProcurementPart  .
	?this a epo:PlannedProcurementPart 
}