#title: BT-22-Part
#description: The corresponding XML element is /*/cac:ProcurementProjectLot[cbc:ID/@schemeName='Part']/cac:ProcurementProject/cbc:ID. The expected ontology instances are epo: epo:PlannedProcurementPart / adms:Identifier / rdf:PlainLiteral .
#xpath: /*/cac:ProcurementProjectLot[cbc:ID/@schemeName='Part']/cac:ProcurementProject/cbc:ID

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

ASK WHERE { 
	?this rdf:type epo:PlannedProcurementPart .
	?this epo:hasInternalIdentifier / skos:notation ?value . 
}