#title: BT-118-NoticeResult-Currency
#description: The corresponding XML element is /*/ext:UBLExtensions/ext:UBLExtension/ext:ExtensionContent/efext:EformsExtension/efac:NoticeResult/efbc:OverallMaximumFrameworkContractsAmount/@currencyID. The expected ontology instances are epo: epo:Notice / epo:NoticeAwardInformation / epo:MonetaryValue / at-voc:currency .
#xpath: /*/ext:UBLExtensions/ext:UBLExtension/ext:ExtensionContent/efext:EformsExtension/efac:NoticeResult/efbc:OverallMaximumFrameworkContractsAmount/@currencyID

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
	?this rdf:type epo:Notice .
	?this epo:announcesNoticeAwardInformation / epo:hasMaximumFrameworkAgreementAwardedValue / epo:hasCurrency ?value . 
}