= TED-RDF eForms Mapping

The TED-RDF eForms Mapping project prescribes packages (or _suites_) of data transformation rules and related artefacts, for digital public procurement notices published on the https://ted.europa.eu/en[Tenders Electronic Daily (TED) website] by the https://op.europa.eu/en/home[Publications Office of the European Union (OP)], based on the https://single-market-economy.ec.europa.eu/single-market/public-procurement/digital-procurement/eforms_en[eForms legislative standard].

The transformation is based on model mapping between the original https://www.w3.org/XML/[XML] format of the TED eForm notices, and the https://docs.ted.europa.eu/EPO/latest/index.html[eProcurement ontology (ePO)], producing data in the https://www.w3.org/RDF/[RDF] format for https://joinup.ec.europa.eu/collection/nifo-national-interoperability-framework-observatory/solution/eif-toolbox/interoperability-layer-5-semantic-interoperability[semantic data interoperability]. This transformation, which is documented here and is available in this https://github.com/OP-TED/ted-rdf-mapping-eforms/[GitHub repository], is the next iteration of the https://github.com/OP-TED/ted-rdf-mapping[RDF mapping initiative], which was conceived for the https://ted.europa.eu/en/simap/standard-ted-schema-forms-in-pdf["TED schema" standard forms (SF)], an older notice standard that is concurrently supported by the OP.

These RDF mapping projects, together with a https://github.com/OP-TED/ted-rdf-conversion-pipeline[pipeline system for automatic XML-RDF data conversion], are collectively known as the https://docs.ted.europa.eu/SWS/index.html[TED Semantic Web Service (TED-SWS)]. As the groundwork for XML-RDF transformation was already set by the SF mapping project, *much of the https://docs.ted.europa.eu/SWS/mapping_suite/index.html[existing documentation] is still applicable for eForms.*
Therefore, the focus of this document is mainly on the differences between SF and eForms mapping.

