= How to use these mapping packages?


== Software Requirements

Users need only to install the following external software tools, libraries
and/or runtimes if developing and testing the RML mappings:

- Java 11+ (tested up to 21)
- RMLMapper-Java==v6.2.2

RMLMapper is currently tied to v6.2.2 because of an
https://github.com/RMLio/rmlmapper-java/issues/236[issue with conditional
instantiation] (which was later
https://github.com/RMLio/rmlmapper-java/blob/144f9b4cb1ca3c7174f9453f28ec626996c19020/CHANGELOG.md[fixed]) and incompatibility of our rules with later versions.


==MSSDK


== Tooling

=== Mapping Suite SDK

The https://github.com/meaningfy-ws/mapping-suite-sdk[Mapping Suite SDK], or MSSDK, is a software development kit (SDK) designed to standardize reading, writing, and validating mapping packages.



=== RMLMapper for development

For development, simple https://github.com/RMLio/rmlmapper-java[RMLMapper] commands (which the SF tools use) can be employed directly, for example:

```
rmlmapper -m $MAPPINGS_FOLDER/* -s turtle > $OUTPUT_FILE
```

where the `$MAPPING_FOLDER` is a folder with RML files, and
`$OUTPUT_FILE` is the desired RDF output file, usually suffixed with the `.ttl`
extension (for the Turtle serialization as provided with the `-s` argument).

The RML rules expect a data file path `data/source.xml` relative to where this
command is run from. In the current package structure, this implies that a
temporary `data` folder is created next to the `test_data` folder with a
desired test data file (whether or not already bundled in the package) copied
as `source.xml`, under `mappings/$PACKAGE_FOLDER`:

```
mappings
mappings/package_eforms_sdk1.9_epo5.2
mappings/package_eforms_sdk1.9_epo5.2/data
mappings/package_eforms_sdk1.9_epo5.2/data/source.xml
mappings/package_eforms_sdk1.9_epo5.2/test_data
mappings/package_eforms_sdk1.9_epo5.2/test_data/sdk_examples_cn-1.9
mappings/package_eforms_sdk1.9_epo5.2/test_data/sdk_examples_cn-1.9/cn_24_maximal.xml
...
```
