#title: OPP-040-Procedure-List
#description: The corresponding XML element is /*/cac:ProcurementProject/cac:ProcurementAdditionalType[cbc:ProcurementTypeCode/@listName='transport-service']/cbc:ProcurementTypeCode/@listName. 
#xpath: /*/cac:ProcurementProject/cac:ProcurementAdditionalType[cbc:ProcurementTypeCode/@listName='transport-service']/cbc:ProcurementTypeCode/@listName

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
	?this rdf:type epo:Procedure .
	?this epo:isSubjectToTerm / epo:hasTransportServiceType ?value .   FILTER ( ISIRI(?value) && CONTAINS(str(?value), 'europa.eu/') ) 
}