#title: BT-22-Procedure-Scheme
#description: The corresponding XML element is /*/cac:ProcurementProject/cbc:ID/@schemeName. The expected ontology instances are epo: epo:Procedure / adms:Identifier / rdf:PlainLiteral .
#xpath: /*/cac:ProcurementProject/cbc:ID/@schemeName

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
	?this rdf:type epo:Procedure .
	?this epo:hasInternalIdentifier / epo:hasScheme ?value . 
}