#title: BT-781-Lot-Language
#description: The corresponding XML element is /*/cac:ProcurementProjectLot[cbc:ID/@schemeName='Lot']/cac:ProcurementProject/cac:PlannedPeriod/cbc:Description/@languageID. The expected ontology instances are epo: epo:Lot / epo:ContractTerm / rdf:langString .
#xpath: /*/cac:ProcurementProjectLot[cbc:ID/@schemeName='Lot']/cac:ProcurementProject/cac:PlannedPeriod/cbc:Description/@languageID

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
	?this rdf:type epo:Lot .
	?this epo:foreseesContractSpecificTerm / epo:hasExceedingDurationJustification ?value .   FILTER(datatype(?value) = rdf:langString) 
}