#title: BT-578-Lot-List
#description: The corresponding XML element is /*/cac:ProcurementProjectLot[cbc:ID/@schemeName='Lot']/cac:TenderingTerms/cac:SecurityClearanceTerm/cbc:Code/@listName. The expected ontology instances are epo: epo:Lot / epo:SecurityClearanceTerm / xsd:boolean .
#xpath: /*/cac:ProcurementProjectLot[cbc:ID/@schemeName='Lot']/cac:TenderingTerms/cac:SecurityClearanceTerm/cbc:Code/@listName

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

ASK WHERE { 
	?this rdf:type epo:Lot .
	?this epo:isSubjectToLotSpecificTerm / epo:isSecurityClearanceRequired ?value .   FILTER ( datatype(?value) = xsd:boolean ) 
}