#title: BT-300-Procedure
#description: The corresponding XML element is /*/cac:ProcurementProject/cbc:Note. 
#xpath: /*/cac:ProcurementProject/cbc:Note

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
	?this rdf:type epo:PlannedProcurement .
	?this epo:hasAdditionalInformation ?value . 
}